name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Pastikan path ini benar menunjuk ke file CSV di dalam folder MLproject
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repo
      - uses: actions/checkout@v3

      # 2. Siapkan Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # 3. Cek Environment (Debugging)
      - name: Check Env
        run: |
          echo "Lokasi CSV: $CSV_URL"
          ls -R

      # 4. Install MLflow dan library pendukung
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn numpy

      # 5. Jalankan Training
      # Perintah ini akan menjalankan project yang ada di folder 'MLproject'
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      # 6. SIMPAN HASIL (Commit & Push balik ke GitHub)
      - name: Save mlruns to repo
        run: |
          # Mengambil identitas dari Secrets yang Anda buat tadi
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          
          # Menambahkan folder hasil training (mlruns)
          git add mlruns/
          
          # Commit perubahan (jika ada file baru)
          # "|| echo..." agar tidak error jika tidak ada perubahan
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"
          
          # Push ke branch MAIN
          git push origin main