name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn numpy

      # Jalankan Training (Nanti akan menghasilkan model besar)
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      # --- SIDE QUEST: SETUP GIT LFS ---
      - name: Set up Git LFS
        run: |
          # Konfigurasi User
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          
          # Install & Setup LFS
          git lfs install
          # Lacak semua file di dalam folder mlruns
          git lfs track "mlruns/**"
          git add .gitattributes
          
          # Commit file .gitattributes (agar GitHub tahu kita pakai LFS)
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main
      

      # --- METODE BARU: UPLOAD KE GOOGLE DRIVE ---
      
      - name: Install Python dependencies for Drive
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }} 
        run: |
          # 1. KOMPRES FOLDER (INI YANG KEMARIN KURANG)
          # Perintah ini akan membungkus folder 'mlruns' menjadi file 'mlruns_backup.zip'
          zip -r mlruns_backup.zip mlruns/
          
          # 2. Jalankan script upload
          python MLproject/upload_to_gdrive.py


      # --- SAVE HASIL (Support File Besar) ---
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          
          # Paksa add folder mlruns
          git add -f mlruns/
          git commit -m "Save mlruns (Large Model) from CI run" || true
          git push origin main
